# mini-gen/k8s-manifests/k8s-manifests.yaml
# This manifest is FIXED to use dynamic tags and imagePullSecrets.

---

# 1. ConfigMap for Environment Variables (API Key)
apiVersion: v1
kind: ConfigMap
metadata:
  name: textgen-config
data:
  GROQ_API_KEY: $GROQ_API_KEY

---

# 2. TextGen (Backend) Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: textgen-deployment
  labels:
    app: textgen
spec:
  replicas: 1
  selector:
    matchLabels:
      app: textgen
  template:
    metadata:
      labels:
        app: textgen
    spec:
      # FIX 1: ADD IMAGE PULL SECRET
      imagePullSecrets:
        - name: docker-hub-secret
      containers:
        - name: textgen-api
          # FIX 2: USE DYNAMIC TAG VARIABLE
          image: consultbibek/mini-gen-textgen:$TEXTGEN_TAG
          # FIX 3: USE ALWAYS TO FORCE PULL
          imagePullPolicy: Always
          ports:
            - containerPort: 5001
          env:
            - name: GROQ_API_KEY
              valueFrom:
                configMapKeyRef:
                  name: textgen-config
                  key: GROQ_API_KEY

---

# 3. TextGen (Backend) Service
apiVersion: v1
kind: Service
metadata:
  name: textgen
  labels:
    app: textgen
spec:
  type: ClusterIP
  selector:
    app: textgen
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001

---

# 4. Frontend Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      # FIX 1: ADD IMAGE PULL SECRET
      imagePullSecrets:
        - name: docker-hub-secret
      containers:
        - name: frontend-web
          # FIX 2: USE DYNAMIC TAG VARIABLE
          image: consultbibek/mini-gen-frontend:$FRONTEND_TAG
          # FIX 3: USE ALWAYS TO FORCE PULL
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: TEXTGEN_HOST
              value: "http://textgen:5001"

---

# 5. Frontend (Web UI) Service
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    app: frontend
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000