# mini-gen-search/k8s-manifests.yaml
# Complete Manifest for Hybrid LLM/RAG Architecture

---

# 1. Qdrant Persistent Volume Claim (PVC)
# Defines storage for the vector index persistence.
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qdrant-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi # Adjust size as needed

---

# 2. Qdrant Service
# Exposes Qdrant's port 6333 internally using a ClusterIP.
apiVersion: v1
kind: Service
metadata:
  name: qdrant-service
  labels:
    app: qdrant
spec:
  selector:
    app: qdrant
  ports:
    - port: 6333
      targetPort: 6333
  type: ClusterIP

---

# 3. Qdrant Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qdrant-deployment
  labels:
    app: qdrant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qdrant
  template:
    metadata:
      labels:
        app: qdrant
    spec:
      containers:
        - name: qdrant
          image: qdrant/qdrant:latest # Use a stable tag
          ports:
            - containerPort: 6333
          volumeMounts:
            - name: qdrant-storage
              mountPath: /qdrant/storage
      volumes:
        - name: qdrant-storage
          persistentVolumeClaim:
            claimName: qdrant-pvc

---

# 4. ConfigMap for Environment Variables (API Key)
apiVersion: v1
kind: ConfigMap
metadata:
  name: textgen-service-rag-config
data:
  GROQ_API_KEY: $GROQ_API_KEY

---

# 5. TextGen (Backend) Deployment - RAG Enabled (textgen-deployment-rag)
apiVersion: apps/v1
kind: Deployment
metadata:
# ... (rest of metadata/spec)
  template:
    metadata:
# ...
    spec:
      imagePullSecrets:
        - name: docker-hub-secret
      containers:
        - name: textgen-api
          image: consultbibek/mini-gen-textgen-rag:$TEXTGEN_TAG
          imagePullPolicy: Always
          ports:
            - containerPort: 5001
          env:
            - name: GROQ_API_KEY
              valueFrom:
                configMapKeyRef:
                  name: textgen-service-rag-config
                  key: GROQ_API_KEY
            - name: QDRANT_HOST
              value: "qdrant-service"
            - name: QDRANT_PORT
              value: "6333"
          # Volume mounts for the PDF file (REMOVED)
      # volumes: (REMOVED)

---

# 6. TextGen (Backend) Service
apiVersion: v1
kind: Service
metadata:
  name: textgen-service-rag
  labels:
    app: textgen-rag
spec:
  type: ClusterIP
  selector:
    app: textgen-rag
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001

---

# 7. Frontend Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment-search
  labels:
    app: frontend-search
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-search
  template:
    metadata:
      labels:
        app: frontend-search
    spec:
      imagePullSecrets:
        - name: docker-hub-secret
      containers:
        - name: frontend-web
          image: consultbibek/mini-gen-frontend-search:$FRONTEND_TAG
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: TEXTGEN_HOST
              value: "http://textgen-service-rag:5001"

---

# 8. Frontend (Web UI) Service
apiVersion: v1
kind: Service
metadata:
  name: frontend-service-search
  labels:
    app: frontend-search
spec:
  type: NodePort
  selector:
    app: frontend-search
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000